name: "Documentation"

on:
    workflow_dispatch:
    # push:
    #  branches: [ "main" ]
    # pull_request:
    #  branches: [ "main" ]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false